# Release build override to avoid Expo lintVital failures.
android.injected.testOnly=false
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Dnode.executable=/home/lidruf/.nvm/versions/node/v24.13.1/bin/node
